### ISSUE TITLE
建议增加类似 redux-devtools 的停靠窗口的功能

### ISSUE THREAD

**Issue by GuoChen-WHU** [yize/xswitch#15]
现在的 xswitch 作为一个 popup 出现在浏览器界面上，失去焦点的时候会自动隐藏，编辑的时候很不方便。比如编辑过程中我想从 network 面板去拷贝一段 url，这时候 xswitch 面板就会隐藏掉，拷贝完回来还得再点开界面。
如果能像 redux-devtools 一样，新建一个停靠在屏幕上的窗口，编辑起来会更加方便。

**Comment by yize** [comment]
嗯，收到

**Comment by yize** [comment]
可以更新 XSwitch 到 `1.5.0`。
![image](https://user-images.githubusercontent.com/1578814/37126022-1fc8f282-22aa-11e8-994d-724c18821ff9.png)
