### ISSUE TITLE
有打算支持分组开关的功能吗？

### ISSUE THREAD

**Issue by xdlrt** [yize/xswitch#16]
目前只有一个全局开关，多项目并行的时候不太方便。

**Comment by yize** [comment]
计划中，最近比较忙，抱歉

**Comment by xdlrt** [comment]
感谢，期待一下

**Comment by fa-ge** [comment]
确实，多环境多项目切换时有点不方便。

**Comment by xiaofan10** [comment]
目前手头只维护一个项目呢，完全够用哈，使用也超级方便，期待大佬二次开发

**Comment by xdlrt** [comment]
https://github.com/xdlrt/xproxy
在这个项目的启发下用React重构了一下这个项目，能够实现和 xswitch 一样的功能，拓展性更好一些，分组的功能还在构思中，不知道什么样形式比较好。
另外顺便求助如何开通 chrome 插件的开发者权限，没办法付认证的费用，目前只能用 load unpacked 功能加载最新的 release 尝试使用。
如果作者大大觉得我这种形式不错的话，可以共建。

**Comment by yize** [comment]
@xdlrt xProxy 挺赞的，之前 xSwitch 也想取名叫 xProxy 的，哈哈。
- 分组的功能，希望还是要有分组、多选分组的功能。类似内网 iHost 的交互方案。
- Chrome 插件的开发者权限很久以前申请的，没办法付认证的费用是因为信用卡吗？
- 之前其实也想过通过 React 来搞，主要因为懒。
- 采用 Code 的形式，后续更方便导入导出。active 单条的这个交互，也是可以做的，可以参考 vscode 的配置部分。
- 之前也想加一个非 Code 模式的面板作为互切的。
- 欢迎共建。

**Comment by xdlrt** [comment]
@yize 
- iHost的方案应该可行，我尝试一下
- 是的，没有国外的信用卡可以付认证费，不过可以共建一下以xSwitch的名义发
- 导入导出这个之前没想到，后续想想怎么提供这样的能力
- 个人认为，React 作为底层架构相较而言更容易拓展些，大大如果有时间的话可以把 Code 面板融合进来，像导入导出和互切这样的功能就顺理成章的拥有了
