### ISSUE TITLE
请问能否代理到本地文件或者直接定义代理数据？

### ISSUE THREAD

**Issue by lilijialiang** [yize/xswitch#20]
如题，感觉每次要代理都要放到另外一个地方比较麻烦。所以能否代理到本地的 json 文件或者直接可以在插件上定义代理返回的数据？

**Comment by yize** [comment]
现在能支持，就是不是太友好。下面的将 https://www.taobao.com 上的一段 CDN URL 替换为一段 JavaScript。

```json
[
  "https://g.alicdn.com/??kissy/k/6.2.4/seed-min.js,kg/global-util/1.0.7/index-min.js,tb/tracker/4.3.3/index.js,kg/tb-nav/2.5.3/index-min.js,secdev/sufei_data/3.3.5/index.js",
  "data:text/javascript,alert(1);"
]
```

**Comment by yize** [comment]
@lilijialiang 本地的，简单的方式，就是直接通过 anywhere 启动下，直接用就好。这个插件主要就是用来代理到本地使用的。 see https://yuque.com/jiushen/blog/xswitch-readme
