### ISSUE TITLE
缓存失效问题

### ISSUE THREAD

**Issue by jiakme** [yize/xswitch#34]
对于不代理的网站, 启用该插件会使得js/css等资源一直从网络中请求, 并不走本地缓存.

**Comment by yize** [comment]
插件有选项，可以关闭清除缓存。

**Comment by jiakme** [comment]
@yize 我只看到是否启用的选项, 关闭清除缓存的选项我并没有看到, 能够说明一下哪里有文档或者麻烦提供一下更详细的说明, 谢谢.

**Comment by yize** [comment]
@jiakme 在插件 icon 右键，选项
