### ISSUE TITLE
the plugin icon in private browser mode is not recognizable enough

### ISSUE THREAD

**Issue by SurfaceW** [yize/xswitch#6]
like this:

![image](https://user-images.githubusercontent.com/5323168/35084888-196e8556-fc61-11e7-9f4b-d388b45b0a6b.png)

I think an icon with white-color stroked should be fine.

**Comment by yize** [comment]
Changed to blue icon.

![image](https://user-images.githubusercontent.com/1578814/35128327-fb9839a6-fcf0-11e7-8c40-14fa39539570.png)
